# Generated by Django 5.2.13 on 2026-04-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="requirement",
            name="req_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="task",
            name="task_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
