# Generated by Django 5.2.7 on 2026-03-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deletion_requested_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='deletion_requested_by_pm',
            field=models.BooleanField(default=False),
        ),
    ]
