# Generated by Django 5.2.13 on 2026-04-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_project_project_id_requirement_req_id_task_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="comments/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="moduleforumpost",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="forum_posts/%Y/%m/"
            ),
        ),
    ]
