# Generated by Django 5.2.7 on 2026-03-28 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('tasks', '0003_systemsettings_knowledgebasenote_systemissue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Build & Test', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('trigger_commit', models.CharField(blank=True, help_text='Git commit hash', max_length=100)),
                ('triggered_by', models.CharField(blank=True, help_text='User or webhook name', max_length=100)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='tasks.project')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='e.g. v1.0.0', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Release notes (Markdown supported)')),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(blank=True, help_text='Build artifacts', related_name='releases', to='files.projectfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='tasks.project')),
            ],
            options={
                'ordering': ['-release_date'],
                'unique_together': {('project', 'version')},
            },
        ),
    ]
