# Generated by Django 5.2.13 on 2026-04-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_comment_attachment_moduleforumpost_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="release",
            name="is_prerelease",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="release",
            name="tag_name",
            field=models.CharField(blank=True, help_text="e.g. v1.0.0", max_length=50),
        ),
    ]
