# Generated by Django 5.2.7 on 2026-04-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_pipelinerun_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='module',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('mechanical', 'Mechanical'), ('optics', 'Optics'), ('simulation', 'Simulation'), ('software', 'Software')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
