# Generated by Django 4.2.29 on 2026-04-03 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_documentaccessright'),
        ('tasks', '0005_project_deletion_requested_at_alter_project_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='tasks.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='release',
            name='name',
            field=models.CharField(default='Legacy Release', help_text='e.g. May 2025 Release', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='release_type',
            field=models.CharField(choices=[('partial', 'Partial (Minor/Nightly)'), ('phase', 'Phase (Major)')], default='partial', max_length=20),
        ),
        migrations.AddField(
            model_name='release',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed')], default='planning', max_length=20),
        ),
        migrations.AddField(
            model_name='release',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.release'),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to='tasks.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project'),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('project', 'name')},
        ),
        migrations.RemoveField(
            model_name='release',
            name='files',
        ),
        migrations.RemoveField(
            model_name='release',
            name='title',
        ),
        migrations.RemoveField(
            model_name='release',
            name='version',
        ),
        migrations.AddField(
            model_name='knowledgebasenote',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_notes', to='tasks.projectmodule'),
        ),
        migrations.AddField(
            model_name='task',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.projectmodule'),
        ),
        migrations.CreateModel(
            name='ReleaseModuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_string', models.CharField(blank=True, max_length=50)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.projectfile')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_versions', to='tasks.projectmodule')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_versions', to='tasks.release')),
            ],
            options={
                'unique_together': {('release', 'module')},
            },
        ),
        migrations.CreateModel(
            name='ModuleMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('designer', 'Designer'), ('developer', 'Developer'), ('tester', 'Tester')], default='developer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tasks.projectmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('module', 'user')},
            },
        ),
    ]
