# Generated by Django 5.2.13 on 2026-05-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_calendarevent_meeting_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="background_color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
        migrations.AddField(
            model_name="project",
            name="button_color",
            field=models.CharField(default="#4f8ef7", max_length=7),
        ),
    ]
