# Generated by Django 5.2.13 on 2026-05-06 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_project_background_color_project_button_color"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="caldav_event_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="google_event_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="UserCalendarSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caldav_url",
                    models.URLField(default="http://localhost:5232/", max_length=500),
                ),
                (
                    "caldav_user",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "caldav_password",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "caldav_calendar_name",
                    models.CharField(default="NexusPM", max_length=100),
                ),
                (
                    "google_calendar_id",
                    models.CharField(default="primary", max_length=255),
                ),
                ("google_oauth_token", models.JSONField(blank=True, null=True)),
                ("is_google_synced", models.BooleanField(default=False)),
                ("is_caldav_synced", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
