# Generated by Django 5.2.7 on 2026-04-04 04:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_assigned_to_task_assignees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='bugreport',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL),
        ),
    ]
