# Generated by Django 5.2.7 on 2026-04-07 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_bugreport_assigned_to_bugreport_assignees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasenote',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kb_notes', to='tasks.project'),
        ),
    ]
