# Generated by Django 5.2.13 on 2026-05-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="branch",
            field=models.CharField(
                choices=[
                    ("koramangala", "IIA, Koramangala"),
                    ("hosakote", "IIA, Hosakote (CREST)"),
                    ("hanle", "IIA, Hanle (IAO)"),
                    ("kavalur", "IIA, Kavalur (VBO)"),
                    ("kodaikanal", "IIA, Kodaikanal (KSO)"),
                    ("gauribidanur", "IIA, Gauribidanur"),
                ],
                default="koramangala",
                max_length=50,
            ),
        ),
    ]
