# Generated by Django 5.2.13 on 2026-04-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="serialnumber",
            options={"ordering": ["-created_at"]},
        ),
    ]
