# Generated by Django 5.0.6 on 2026-04-09 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Inventory Management', max_length=100)),
                ('access_level', models.CharField(choices=[('Full Access', 'Full Access'), ('Read Only', 'Read Only'), ('Manager', 'Manager')], default='Full Access', max_length=50)),
                ('assigned_warehouse', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Admin User',
                'verbose_name_plural': 'Inventory Admin Users',
            },
        ),
    ]
