# Generated by Django 4.2.30 on 2026-04-27 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        ("files", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="filecategory",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="filecategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="files.filecategory",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="filecategory",
            unique_together={("name", "parent", "project")},
        ),
    ]
