# Generated by Django 4.2.29 on 2026-04-03 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_projectmodule_alter_release_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_documentaccessright'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='tasks.projectmodule'),
        ),
        migrations.AddField(
            model_name='documentaccessright',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_rights', to='files.projectfile'),
        ),
        migrations.AddField(
            model_name='documentaccessright',
            name='kb_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_rights', to='tasks.knowledgebasenote'),
        ),
        migrations.AddField(
            model_name='documentaccessright',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access_rights', to=settings.AUTH_USER_MODEL),
        ),
    ]
