# Generated by Django 4.2.29 on 2026-04-03 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_projectmodule_alter_release_unique_together_and_more'),
        ('files', '0003_projectfile_module_documentaccessright_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_files', to='tasks.release'),
        ),
    ]
